name = "rhystmorgan/wine"
version = "0.0.0"
license = "Apache-2.0"
description = "Aiken contracts for project 'rhystmorgan/wine'"

[repository]
user = "rhystmorgan"
project = "wine"
platform = "github"

[[dependencies]]
name = "aiken-lang/stdlib"
version = "1.8.0"
source = "github"
